//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_controle.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class produtos_enviado
    {
        public int Id { get; set; }
        public string Shampoo { get; set; }
        public string Condicionador { get; set; }
        public string Sabonete { get; set; }
    }
}
